engines:
  duplication:
    enabled: true
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        python:
          mass_threshold: 110
  radon:
    enabled: true
    config:
      threshold: "C"
  fixme:
    enabled: true
    exclude_paths:
      - "notebooks/"
  pep8:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - "**.py"
    - "**.sh"
    - "**.md"
