language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
install:
  - pip install -r requirements_test.txt
  - pip install codecov
script:
  - sh test.sh
after_success:
  - codecov
notifications:
  email: false
